### ISSUE TITLE
Typo in readme?

### ISSUE THREAD

**Issue by davidmasp** [google/deepsomatic#1]
Hello!

Thanks for developing this tool, eager to try it out.

I saw what possibly it's a typo in the [readme](https://github.com/google/deepsomatic/blob/b7897395ab9322d9739b32fe046723c42272e140/README.md?plain=1#L42-L43)? both reads normal and tumor refer to the same filepath named `normal.bam`. I know it's not supposed to be a real file but it might be confusing to people if both the normal bam and the tumor bam arguments link to the same file in the "quickstart" code.

```
--reads_normal=${INPUT_DIR}/normal.bam \ **Path to normal bam file.
--reads_tumor=${INPUT_DIR}/normal.bam \ * Path to tumor bam file.
```

Best,
DMP

**Comment by pichuan** [comment]
Thanks @davidmasp . That's a typo and we'll fix it.
