### ISSUE TITLE
Performance regression with a different HCC1395 Illumina library

### ISSUE THREAD

**Issue by omicsnut** [google/deepsomatic#10]
Hi,

First of all, thank you for open sourcing DeepSomatic. Hope that it is going to be a useful tool for the community moving forward.

I am unable to reproduce the variant calling performance results shown in the [Illumina case study page in the docs](https://github.com/google/deepsomatic/blob/r1.6/docs/deepsomatic-illumina-case-study.md), with a different library of the same HCC1395 T/N sample pair from the SEQC2 consortium. WGS_NS_T_1 (https://www.ncbi.nlm.nih.gov/sra/SRX4728475) and WGS_NS_N_1 (https://www.ncbi.nlm.nih.gov/sra/SRX4728425) were used for this purpose as T/N sample pairs. 

* You can find the whole genome T/N (85x/70x) bams for WGS_NS_T_1 and WGS_NS_N_1 here - [gs://lancet2-test-datasets/SEQC2/single_library](https://console.cloud.google.com/storage/browser/lancet2-test-datasets/SEQC2/single_library)
* We downsampled coverage to the same T/N coverage as in the case study to check if makes a difference. (It didn't)
* Two runs of the case study data were performed with two evaluation tools ([RTG vcfeval](https://github.com/RealTimeGenomics/rtg-tools) & [hap.py](https://github.com/Illumina/hap.py)) to show that the tools don't change the peformance results.

Results from all the runs that were tested are summarized in this google sheet. Red cells highlights the significant loss in precision when using the different library compared to the dataset provided in the case study example shown in green. 
https://docs.google.com/spreadsheets/d/1ReOMR85lPvC_Y6xZCPiY1SOFRDmQ5NXTSMUL0rOaaNA/edit?usp=sharing

1. Do you have any thoughts or suggestions on why there is such a big difference in precision when using a different library of the same sample? Is this expected? If there is anything I am missing or doing incorrectly, please do let me know.
2. It might be useful in general to document which specific library (among the SEQC2 consortium datasets - https://sites.google.com/view/seqc2/home/sequencing) is being used in the case study.

**Comment by kishwarshafin** [comment]
@omicsnut ,

I will first give you the source of the input files:

Normal used in case study: https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/seqc/Somatic_Mutation_WG/data/WGS/WGS_NS_N_1.bwa.dedup.bam

Tumor used in case study:  https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/seqc/Somatic_Mutation_WG/data/WGS/WGS_NS_T_1.bwa.dedup.bam

So it's the "NovaSeq at Illumina". One thing that can be done quickly is to look at the header of the BAM file used for the case study and the BAM you are using as input to see if the pre-processing was done similarly for both.

**Comment by omicsnut** [comment]
@kishwarshafin,

It looks like the attached bams do not have any special pre-processing in the header other than just running bwa mem alignment of the reads to the reference. But I'm assuming based on the file naming duplicate marking step has also been performed on the case study bams.

The bams I'm using as input were built using the [NYGC cancer pipeline](https://bioinformatics.nygenome.org/software/nygc-cancer-pipeline/) - which essentially boil down to the same main steps in general, other than two additional steps of short read marking (mainly to identify bacterial read contamination) and BQSR.
I don't think short read marking should affect DeepSomatic in any way since it doesn't really remove reads. 

So it looks like we are indeed using the exact same libraries as well. WGS_NS_T_1 and WGS_NS_N_1. Would BQSR affect the precision of DeepSomatic by thus magnitude?

**Comment by kishwarshafin** [comment]
@omicsnut,

Thank you for sharing your findings so promptly. DeepSomatic is trained on all libararies presented in seqc2, so I was unsure if library difference could be the reason.

We have not tested if BQSR does affect the quality of variant calls in DeepSomatic, however, it is important to note that we use base quality as an input channel for the model. Do you possibly have the BAM files without BQSR or the raw fastq files to see if this behavior can be tested? I think that would be the natural next test to figure out exactly what's going on.

**Comment by omicsnut** [comment]
@kishwarshafin - We do not have the BAM files without BQSR readily available. But you can find the raw reads (fastq) for these samples here on SRA - WGS_NS_T_1 (https://www.ncbi.nlm.nih.gov/sra/SRX4728475) and WGS_NS_N_1 (https://www.ncbi.nlm.nih.gov/sra/SRX4728425).

**Comment by proteinosome** [comment]
Just to add to this issue, I'm seeing the same poor indel precision with WGS_NS_N_1 and WGS_NS_T_1. I am using CRAM files from the [Sarek v3.4.0](https://nf-co.re/sarek/3.4.0) pipeline after mark duplicate (No base quality recalibration). 72X tumor and 60X normal for all numbers below. 

```
type      total.truth   total.query   tp      fp     fn     unk   ambi   recall           recall_lower     recall_upper     recall2          precision        precision_lower   precision_upper   na    ambiguous   fp.region.size   fp.rate          sompyversion             
-   -------   -----------   -----------   -----   ----   ----   ---   ----   --------------   --------------   --------------   --------------   --------------   ---------------   ---------------   ---   ---------   --------------   --------------   -------------------------
0   indels    1602          2964          1508    1456   94     0     0      0.941323345818   0.929010892348   0.952043403544   0.941323345818   0.508771929825   0.490773215355    0.52675352229     0.0   0.0         2875001522       0.506434514507   som.py-v0.3.8-17-gf15de4a
1   SNVs      39447         39350         37574   1776   1873   0     0      0.952518569219   0.95038662855    0.954584109645   0.952518569219   0.954866581957   0.952781883866    0.956884370837    0.0   0.0         2875001522       0.617738803409   som.py-v0.3.8-17-gf15de4a
5   records   41049         42315         39082   3233   1967   0     0      0.952081658506   0.949983440209   0.954116129368   0.952081658506   0.923596833274   0.921036801718    0.926098920456    0.0   0.0         2875001522       1.12452114382    som.py-v0.3.8-17-gf15de4a
```

For comparison, these are the Strelka2 and Mutect2 performance using the same sample from Sarek pipeline. Surprisingly low precision too, but better than DeepSomatic, with lower recall.

```
Strelka2

    type      total.truth   total.query   tp      fp     fn     unk   ambi   recall           recall_lower     recall_upper     recall2          precision        precision_lower   precision_upper   na    ambiguous   fp.region.size   fp.rate          sompyversion             
-   -------   -----------   -----------   -----   ----   ----   ---   ----   --------------   --------------   --------------   --------------   --------------   ---------------   ---------------   ---   ---------   --------------   --------------   -------------------------
0   indels    1602          1961          1463    498    139    0     0      0.913233458177   0.898701919585   0.926273715935   0.913233458177   0.746047934727   0.726429962727    0.764940226369    0.0   0.0         2875001522       0.173217299605   som.py-v0.3.8-17-gf15de4a
1   SNVs      39447         38565         36991   1574   2456   0     0      0.937739245063   0.935322617332   0.94009164081    0.937739245063   0.959185790224   0.957176480151    0.961126181148    0.0   0.0         2875001522       0.547477971039   som.py-v0.3.8-17-gf15de4a
5   records   41049         40526         38454   2072   2595   0     0      0.936782869254   0.934397876042   0.939106271938   0.936782869254   0.948872328875   0.946695758254    0.950984787719    0.0   0.0         2875001522       0.720695270644   som.py-v0.3.8-17-gf15de4a

Mutect2

    type      total.truth   total.query   tp      fp     fn     unk   ambi   recall           recall_lower     recall_upper     recall2          precision        precision_lower   precision_upper   na    ambiguous   fp.region.size   fp.rate          sompyversion             
-   -------   -----------   -----------   -----   ----   ----   ---   ----   --------------   --------------   --------------   --------------   --------------   ---------------   ---------------   ---   ---------   --------------   --------------   -------------------------
0   indels    1602          2000          1421    579    181    0     0      0.887016229713   0.870818058307   0.901817624986   0.887016229713   0.7105           0.690329781957    0.730061471041    0.0   0.0         2875001522       0.201391197733   som.py-v0.3.8-17-gf15de4a
1   SNVs      39447         36180         35757   423    3690   0     0      0.906456764773   0.903553375987   0.909300511453   0.906456764773   0.988308457711   0.987161394007    0.989377406478    0.0   0.0         2875001522       0.147130356893   som.py-v0.3.8-17-gf15de4a
5   records   41049         38627         37178   1449   3871   0     0      0.905698068162   0.902842311803   0.908496616907   0.905698068162   0.962487379294   0.960557687454    0.96434776804     0.0   0.0         2875001522       0.503999733187   som.py-v0.3.8-17-gf15de4a
```

**Comment by AndrewCarroll** [comment]
Hi @proteinosome 

Thank you for filing this, sorry that I'm only now seeing this. That is a low number for Indel precision. I am wondering if this reflects something in the preparation (e.g. this is a highly PCR amplified sample), something in how Sarek processes the alignments, or something else.

Have you used Sarek with our direct case study files and do you observe this lower precision  with those direct files?

Thank you,
Andrew

**Comment by kishwarshafin** [comment]
@proteinosome and @omicsnut ,

So it does not look like BQSR is the issue. Is it possible for you to share your bam to see if we can recreate the issue internally and try to see where the differences are coming from?

**Comment by proteinosome** [comment]
@kishwarshafin happy to upload the data if you could point me to somewhere I can upload to!

**Comment by omicsnut** [comment]
@kishwarshafin - Thanks for the update. It would be great if you can reproduce the issue on your end with BQSR bams. Ideally, it would be nice to have DeepSomatic be agnostic of whether BQSR was run or not as none of the other variant callers seem to be affected that much by it.

 You can find the Tumor (`HCC1395_*.bam`) and Normal (`HCC1395BL_*.bam`) bam file at this google storage bucket path – `gs://lancet2-test-datasets/SEQC2/single_library`

The pre-processing pipeline that was used to generate these BAMs starting from the raw data (WGS_NS_T_1 – https://www.ncbi.nlm.nih.gov/sra/SRX4728475 and WGS_NS_N_1 – https://www.ncbi.nlm.nih.gov/sra/SRX4728425) is described in this paper – https://bioinformatics.nygenome.org/3-cancer-cell-lines-on-2-sequencers/. 

Briefly, the BAMs were generated by bwa mem alignment, followed by duplicate marking with Picard and BQSR.

**Comment by kishwarshafin** [comment]
@omicsnut,

Thank you for the files. In absense of the sarek files, I ran your files and was able to reproduce the differences. One of the things that is very different between the `WGS_NS_T` files vs `HCC1395_SAMN10102573_SRR7890893` is the amount of examples generated. It seems like `HCC1395_SAMN10102573_SRR7890893` generates a total of 2817024 examples vs 564224 in chr1 with `WGS_NS_T` files. I believe the data are quiet different between these two libraries as we are picking up 5x more candidates.

Then I looked at our training manifest and it seems we only train on `*_NS_*` bams.

```bash
# These are the bams present in our training manifest:
WGS_NS_T_1.bwa.dedup.bam
WGS_NS_T_2.bwa.dedup.bam
WGS_NS_T_3.bwa.dedup.bam
WGS_NS_T_4.bwa.dedup.bam
WGS_NS_T_5.bwa.dedup.bam
WGS_NS_T_6.bwa.dedup.bam
WGS_NS_T_7.bwa.dedup.bam
WGS_NS_T_8.bwa.dedup.bam
WGS_NS_T_9.bwa.dedup.bam
```

Which could be the reason it's more accurate on one library prep. 

Next, I will add the other bams to the manifest and train a new model to see if that improves the INDEL performance on your data.

**Comment by omicsnut** [comment]
@kishwarshafin Thanks for taking the time to looking into this issue. 

One thing I would like to add is that the BAMs shared in the bucket are from the exact same library `*_NS_*` bams from your training manifest. The only difference between your training manifest bams and the ones I shared are the additional step of BQSR in the bam creation process.

The raw data used to generate the HCC1395_SAMN10102573_SRR7890893 T/N bams were generated from the two following SRA links.
WGS_NS_T_1 (https://www.ncbi.nlm.nih.gov/sra/SRX4728475)
WGS_NS_N_1 (https://www.ncbi.nlm.nih.gov/sra/SRX4728425)

**Comment by kishwarshafin** [comment]
@omicsnut ,

Sorry for such a long delay, we had to figure out a lot of things on the training side. We currently have a "beta" version of the next model, can you please try out the following docker and see if your results improve:

```bash
google/deepsomatic:v17_rc0_07012024
google/deepsomatic:v17_rc0_07012024-gpu
```

**Comment by omicsnut** [comment]
@kishwarshafin – Thanks for reaching out with the update. We will run the same tests with the beta version and report back soon.

**Comment by omicsnut** [comment]
@kishwarshafin – It looks like the v17_rc0 version does fix the loss in precision that was previously present when run on BQSR bams, albeit at a small cost of lower sensitivity. But the gain in precision is much higher than loss in sensitivity.

Attached sheet has benchmarking results for both BQSR and non-BQSR bams on chr1 HCC1395.
https://docs.google.com/spreadsheets/d/1tJr7bTFzvcFihfKJyDwoT3kly9IOZQjjiYN4uwmql8U/edit?gid=0#gid=0

In case it's useful for you to look through the run log files – Here's the link to the tarball with full directories for the 4 deepsomatic runs – https://storage.googleapis.com/lancet2-test-datasets/SEQC2/HCC1395_chr1_bqsr_test_results.tar.gz

**Comment by kishwarshafin** [comment]
Great! Thank you for reporting! I looked the logs and they look good to me! We will make these models available in the next release officially.
