### ISSUE TITLE
Feature request: Output normal allelic depth

### ISSUE THREAD

**Issue by proteinosome** [google/deepsomatic#11]
@kishwarshafin, likely not a priority at this point, but outputting normal depth (as a separate sample column) could be useful for:

1. Tools that ingest somatic VCF, e.g. Purple in hmftools suite for purity/ploidy estimation
2. Manual inspection and QC visualization of variants

Thank you!

**Comment by kishwarshafin** [comment]
Hi @proteinosome ,

Thank you for the suggestion. I will note these requests.
