### ISSUE TITLE
Nanopore model availability

### ISSUE THREAD

**Issue by ChangqingW** [google/deepsomatic#12]
I wonder if there are plans for training DeepSomatic for Nanopore samples anytime soon? If not, would you expect the performance to deteriorate greatly if I were to select the PacBio model for our Nanopore RNA-seq samples?

**Comment by kishwarshafin** [comment]
Hi @ChangqingW ,

Currently we do not have a ONT model publicly available with the release and we do not expect the pacbio model to work for nanopore. Can you please reach us by sending an email to shafin@google.com so we can assist you further?

**Comment by kishwarshafin** [comment]
Handled in email.
