### ISSUE TITLE
Output normal sample in the VCF

### ISSUE THREAD

**Issue by bcantarel** [google/deepsomatic#14]
It would be great if deep somatic could output the normal sample in the VCF similar to Mutect and other somatic callers, this to ensure end-users that their somatic variants have little (1 or 2) or no reads in the normal sample.

**Comment by kishwarshafin** [comment]
hi @bcantarel ,

Currently, the VCF is tagged with "GERMLINE" and "SOMATIC" for each variant. However, please do not use the output of DeepSomatic for downstream germline variation analysis. We exclude a lot of variant that appear to be germline in pre-processing without reporting them in the VCF. The best idea is to run DeepVariant separately on the normal sample and use it for analysis.

Also, apologies for the delayed response.

**Comment by pichuan** [comment]
Hi @bcantarel , I'll close this issue now. Feel free to reopen or open a new issue if you have any follow up questions.
