### ISSUE TITLE
How to filter variant sites after running deepsomatic

### ISSUE THREAD

**Issue by DayTimeMouse** [google/deepsomatic#15]
Hi,

How to filter variant sites after running deepsomatic. Is it enough to extract only the variant sites marked as 'PASS' in the FILTER column of the VCF file? 

What are the recommended methods and thresholds for filtering? 

Moreover, what methods can be used to filter for multi-allelic variant sites?

Best wishes.

**Comment by pichuan** [comment]
> Hi,
> 
> How to filter variant sites after running deepsomatic. Is it enough to extract only the variant sites marked as 'PASS' in the FILTER column of the VCF file?
> 
> What are the recommended methods and thresholds for filtering?

Hi @DayTimeMouse ,
from the perspective of DeepSomatic, if you get the variants marked as `PASS`, those are the ones that DeepSomatic is calling as somatic variant. If you have further databases to compare against, it is possible that you want to do downstream filtering from there. But that will depend on your use case.


> 
> Moreover, what methods can be used to filter for multi-allelic variant sites?

Can you give an example of what you want to filter?

> 
> Best wishes.

**Comment by kishwarshafin** [comment]
@DayTimeMouse , Closing this for now. Please feel free to reopen if you have further questions.
