### ISSUE TITLE
Why all the GT of the PASS variant site is 1/1? use deepsomatic

### ISSUE THREAD

**Issue by DayTimeMouse** [google/deepsomatic#16]
Hi,

Why all the GT of the PASS variant site is 1/1? use deepsomatic.

chr1 91748 . C T 10 PASS . GT:GQ:DP:AD:VAF:PL 1/1:10:61:48,13:0.213115:9,19,0

Best wishes.

**Comment by pichuan** [comment]
Hi @DayTimeMouse ,
I believe this question is the same as https://github.com/google/deepsomatic/issues/3

Please take a look at that thread. I'll close this issue, but if you have more questions after reading that, please feel free to reopen this one, or open a new issue. Thanks!
