### ISSUE TITLE
gvcf

### ISSUE THREAD

**Issue by minw2828** [google/deepsomatic#18]
Hello, 

Thank you for producing the tool. :)

I am wondering why the output includes a gvcf file. How do you think I should use it? Is the gvcf file prepared for the future to detect somatic variants in a large cohort? 

Many thanks,
Min

**Comment by kishwarshafin** [comment]
hi @minw2828,

Yes, although the gvcf outputs can be cumbersome it does allow to do cohort level somatic variant analysis if anyone is interested in that. We thought it would be a nice use-case to support so we have GVCF support. It is optional, so if you don't need it, you can turn it off without any issues. Turning it off will improve your runtime.

**Comment by minw2828** [comment]
Hi @kishwarshafin,

Thank you! That's helpful. 

Is the way to turn off GVCF simply leave out the following line?
`--output_gvcf=${OUTPUT_DIR}/OUTPUT.g.vcf.gz \ **Path to output gVCF file.`

Many thanks,
Min

**Comment by pichuan** [comment]
Hi @minw2828 ,
Please just remove that line, which should allow you to skip generating the gVCF file.

**Comment by minw2828** [comment]
Thank you @pichuan!
