### ISSUE TITLE
Resuming interrupted run

### ISSUE THREAD

**Issue by kiranchari** [google/deepsomatic#19]
I ran Deepsomatic's WGS_TUMOR_ONLY model using singularity (version: v17_rc1_08082024). I used the run_deepsomatic command but the process was interrupted after 24 hours. Can DeepSomatic resume the job from where it left off, if I re-submit the same command? Thanks!

**Comment by kishwarshafin** [comment]
Hi @kiranchari ,

Currently DeepSomatic can't resume from a broken run. However, if you had set `--intermediate_results_dir ${OUTPUT_DIR}/intermediate_results_dir \` then you can run each step separately. To see each step, run the same command with `--dry_run=true` and it will show you the commands `run_deepsomatic` wraps. But if your run was interrupted during make_examples then it needs to be run from the start.

**Comment by kiranchari** [comment]
Hi @kishwarshafin, yes I used `--intermediate_results_dir`. Looks like the run was interrupted in the `call_variants` step. I see a file called `call_variants_output-00000-of-00001.tfrecord.gz` in `intermediate_results_dir`. Do I need to delete this file before running `call_variants` again? How about the other steps?

this was the output of `dry_run`:

```
***** Running the command:*****
time seq 0 2 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples_somatic --mode calling --ref "/data/reference.fa" --reads_tumor "/data/bams/sample.bam" --examples "/data/deepsomatic/sample/intermediate_results_dir/make_examples_somatic.tfrecord@3.gz" --checkpoint "/opt/models/deepsomatic/wgs_tumor_only" --gvcf "/data/deepsomatic/sample/intermediate_results_dir/gvcf.tfrecord@3.gz" --population_vcfs "/opt/models/deepsomatic/pons/AF_ilmn_PON_CoLoRSdb.GRCh38.AF0.05.vcf.gz" --sample_name_tumor "tumor" --vsc_max_fraction_indels_for_non_target_sample "0.5" --vsc_max_fraction_snps_for_non_target_sample "0.5" --vsc_min_fraction_indels "0.05" --vsc_min_fraction_snps "0.07" --task {}

```

```
***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/data/deepsomatic/sample/intermediate_results_dir/call_variants_output.tfrecord.gz" --examples "/data/deepsomatic/sample/intermediate_results_dir/make_examples_somatic.tfrecord@3.gz" --checkpoint "/opt/models/deepsomatic/wgs_tumor_only"

```

```
***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/data/reference.fa" --infile "/data/deepsomatic/sample/intermediate_results_dir/call_variants_output.tfrecord.gz" --outfile "/data/deepsomatic/sample/sample.vcf.gz" --process_somatic=true --gvcf_outfile "/data/deepsomatic/sample/sample.g.vcf.gz" --nonvariant_site_tfrecord_path "/data/deepsomatic/sample/intermediate_results_dir/gvcf.tfrecord@3.gz"

```

```
***** Running the command:*****
time /opt/deepvariant/bin/vcf_stats_report --input_vcf "/data/deepsomatic/sample/sample.vcf.gz" --outfile_base "/data/deepsomatic/sample/sample"

```

Thanks.

**Comment by kishwarshafin** [comment]
@kiranchari yes, remove that file and run `call_variants` -> `postprocess_variants` -> `vcf_stats_report` (optional)

**Comment by kiranchari** [comment]
Thanks @kishwarshafin. I just noticed that v1.7 was released: https://github.com/google/deepsomatic/releases/tag/v1.7.0. Is there any major difference between release v1.7 and v17_rc1_08082024? In other words, do I need to re-run deepsomatic on my sample with the new release?

**Comment by kishwarshafin** [comment]
@kiranchari the WES model is the same. We only changed ONT and PacBio models to improve runtime performance.

**Comment by kishwarshafin** [comment]
Closing this issue, feel free to reopen if you need.

**Comment by kiranchari** [comment]
Thank you
