### ISSUE TITLE
Where is source code?

### ISSUE THREAD

**Issue by jjv5** [google/deepsomatic#21]
Release tar and zip files do not contain any source. Is it possible to run this without docker? This is hinted at in the readme but it seems like there is a missing section or two.

**Comment by kishwarshafin** [comment]
@jjv5 ,

DeepSomatic uses the same codebase as DeepVariant. To maintain development cadence and not break the simultaneous development branches, the code of DeepSomatic can be found under DeepVariant. For example, r1.7 is available here: https://github.com/google/deepvariant/tree/r1.7 with the run_deepsomatic script available through: scripts/run_deepsomatic.py

**Comment by kishwarshafin** [comment]
If you want to build the dockerfile, it's available here: https://github.com/google/deepvariant/blob/r1.7/Dockerfile.deepsomatic
