### ISSUE TITLE
Tumor-normal mode with rnaseq data

### ISSUE THREAD

**Issue by gianfilippo** [google/deepsomatic#23]
Hi,

is ti possible to run deepsomatic on matched tumor-normal rnaseq samples ? 
from a previous issue, it seems that the WES mode is the way to run this case. Is this tested ?
In deepvariant the "customized_model" options is used to point to a a model trained using RNA-seq data.
Could you please clarify ?

Thanks

**Comment by kishwarshafin** [comment]
Hi @gianfilippo ,

The best suited model for your use-case right now is the WES tumor-normal model. You can find the case-study here: https://github.com/google/deepsomatic/blob/r1.7/docs/deepsomatic-case-study-wes.md. 

We have not tested our models on rnaSEQ data as we didn't have benchmarking data. The [DeepVariant RNASEQ model](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-rnaseq-case-study.md) is for germline variants and is not suitable for somatic variant calling.

**Comment by gianfilippo** [comment]
thanks. The lack of rnaseq benchmarking data is definitely a problem
