### ISSUE TITLE
Feature request: allele depths in FORMAT 

### ISSUE THREAD

**Issue by rowanhowellGE** [google/deepsomatic#24]
Hi,

We have some tools that expect to see allele depths in FORMAT column (ie A,C,G,T or AU,CU,GU,TU) and TIR/TAR for indels. Would be great if there was a way to get these in the vcf output.

Thanks,
Rowan

**Comment by kishwarshafin** [comment]
@rowanhowellGE ,

Can you expand on a bit what your request is? We do report allele depths under `AD` field and frequency under `VAF` field.

**Comment by rowanhowellGE** [comment]
They are described under allelic depth here https://support.illumina.com/help/variantstudio/Content/Vault/Informatics/Sequencing_Analysis/VS/swSEQ_mVS_SomaticVCFs.htm . Basically just count for each allele in tumour sample.

**Comment by kishwarshafin** [comment]
@rowanhowellGE ,

Unfortunately, adding this feature requires a lot of code change including supporting non-standard bases. One workaround could be to use some other software that can give you allele summary for the tumor sample that you can use with the DeepSomatic output. I have a note internally to work on this but I can't tell you when it can be prioritized. I will close this issue.
