### ISSUE TITLE
Feature request: support panel-of-normals (PoN)

### ISSUE THREAD

**Issue by lbeltrame** [google/deepsomatic#25]
Matched tumor-normal analyses can be problematic if the normal sample has issues, is missing for any reason,  or simply has an outlier genotype. A better approach, currently as far as I know only implemented in the Mutect 2 variant caller, is to use a reasonably large panel of normals (10+) to weed out also those variants appearing in a normal population (Mutect 2 flags variants present in at least two samples of the PoN).

Especially in settings where samples can come from archival sources (i.e. hospitals, or biobanks) and thus the normal samples may have not been collected, cannot be collected, or were lost for whatever reason, an approach using a PoN is definitely superior to a tumor-normal matched approach.

**Comment by kishwarshafin** [comment]
Hello @lbeltrame ,

I believe you are referring to the tumor-only mode of DeepSomatic? There are case studies and models for tumor-only mode and we have desribed the method in our [manuscript](https://www.biorxiv.org/content/10.1101/2024.08.16.608331v1.full.pdf)
<img width="602" alt="Screenshot 2024-09-20 at 9 37 03 AM" src="https://github.com/user-attachments/assets/491f5479-5ce7-4e12-82b7-145bf5bfb4b8">

If you are asking about TiN contamination, it's in figure 3B. For PON of DeepSomatic, we use dbSNP, clinvar and 1KGP variants. Please let me know if you have any further questions.

**Comment by kishwarshafin** [comment]
Closing this issue, please feel free to reopen.
