### ISSUE TITLE
parallel: This job failed

### ISSUE THREAD

**Issue by Jiayi-Wang-Joey** [google/deepsomatic#27]
Hi Thanks for your great work.

I encountered this error and not sure how to solve it. I have PacBio scRNA-seq, and want to call variants on the pseudobulk level. 
```
parallel: This job failed:
/opt/deepvariant/bin/make_examples_somatic --mode calling --ref /home/jiayiwang/pacbio/data/genome/GRCh38.primary_assembly.genome.fa --reads_tumor /home/jiayiwang/loggedfs_david_penton/result/align/genome/deduplication/tumor1.aligned.dedup.bam --reads_normal /home/jiayiwang/loggedfs_david_penton/result/align/genome/deduplication/normal1.aligned.dedup.bam --examples '/home/jiayiwang/pacbio/results/variant/DeepSomatic/patient1/intermediate_results_dir/make_examples_somatic.tfrecord@10.gz' --checkpoint /opt/models/deepsomatic/pacbio --alt_aligned_pileup diff_channels --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 25000 --phase_reads --pileup_image_width 99 --norealign_reads --sample_name_normal normal1 --sample_name_tumor tumor1 --sort_by_haplotypes --track_ref_reads --trim_reads_for_pileup --vsc_max_fraction_indels_for_non_target_sample 0.5 --vsc_max_fraction_snps_for_non_target_sample 0.5 --vsc_min_count_snps 1 --vsc_min_fraction_indels 0.1 --vsc_min_fraction_snps 0.02 --task 2

real    198m8.339s
user    1560m45.657s
sys     6m56.691s
```

This is the command I used:
`singularity exec --bind ${INPUT_DIR}:${INPUT_DIR} --bind ${OUTPUT_DIR}:${OUTPUT_DIR} ./deepsomatic-1.7.0.simg run_deepsomatic --model_type=PACBIO --ref=/home/jiayiwang/pacbio/data/genome/GRCh38.primary_assembly.genome.fa --reads_normal=${INPUT_DIR}/normal1.aligned.dedup.bam --reads_tumor=${INPUT_DIR}/tumor1.aligned.dedup.bam --output_vcf=${OUTPUT_DIR}/patient1.vcf.gz --sample_name_tumor="tumor1" --sample_name_normal="normal1" --num_shards=10 --logging_dir=${OUTPUT_DIR}/logs --intermediate_results_dir=${OUTPUT_DIR}/intermediate_results_dir`

If I specify the region=chr1, it works. However, I need to call it on the whole genome. 
Can you help me with this? Thanks in advance!

**Comment by kishwarshafin** [comment]
@Jiayi-Wang-Joey , can you please provide the full log? The parallel: This job failed doesn't provide enough information to provide you useful guidance.

**Comment by Jiayi-Wang-Joey** [comment]
[make_examples_somatic.log](https://github.com/user-attachments/files/17343640/make_examples_somatic.log)

Thanks for your reply!
Yes, for sure. Sorry I should attach it earlier, please see it in the attachment.

**Comment by kishwarshafin** [comment]
@Jiayi-Wang-Joey , seems like your run is failing for this reason:

```bash
I1009 19:24:04.986305 139729885545088 make_examples_core.py:321] Task 7/10: Small Model called 0 candidates
2024-10-09 19:24:55.800588: F ./third_party/nucleus/core/statusor.h:230] Non-OK-status: status_ status: INVALID_ARGUMENT: Invalid interval: reference_name: "KI270442.1" start: 392061 end: 392061
Fatal Python error: Aborted
```

Can you see if `KI270442.1` is present in your input fasta file and the length is correct?

**Comment by Jiayi-Wang-Joey** [comment]
Thanks! I checked:
```
> grep -A 1 ">KI270442.1" GRCh38.primary_assembly.genome.fa | grep -v ">" | tr -d '\n' | wc -c
> 60
```
It seems it has length 60, but `start: 392061 end: 392061` shows length 0?

My fasta file was downloaded from GENCODE and was used for alignment.

**Comment by kishwarshafin** [comment]
@Jiayi-Wang-Joey , can you please look at the associated index file for this fasta and the length? You can grep the contig and it should show up. If the index is wrong then you can just reindex and it should work fine after that.

**Comment by kishwarshafin** [comment]
Closing this, feel free to reopen if you have further questions.
