### ISSUE TITLE
Using Singuarity to run deepsomatic

### ISSUE THREAD

**Issue by Coaxecva** [google/deepsomatic#29]
Hi, I attempted to run `deepsomatic` using Singularity. After converting the Docker image to a `.sif`, I used `--bind` to mount the input and output folders, but encountered the following error. Could you advise on resolving this issue?

`FATAL: container creation failed: mount hook function failure: mount /input/data->/<path-to-bam>/ error: while mounting /input/data: mount source /input/data doesn't exist`

```
singularity exec \
    --bind input/data:/<path-to-bam>/ \
    --bind output:./ \
    <path-to>/deepsomatic_1.7.0.sif \
    run_deepsomatic \
    --model_type=WGS \
    --ref=<path-to>/Homo_sapiens_assembly38.fasta \
    --reads_normal=normal-sample.bam \
    --reads_tumor=tumor-sample.bam \
    --output_vcf=test_deepsomatic_output.vcf.gz \
    --sample_name_tumor="sample1" \
    --sample_name_normal="sample1" \
    --num_shards=$(nproc) \
    --logging_dir=./logs \
    --intermediate_results_dir=./intermediate_results_dir \
    --regions=chr1
```

**Comment by kishwarshafin** [comment]
@Coaxecva , please use absolute path for `--bind input/data`

**Comment by Coaxecva** [comment]
Got it, thank you! So essentially, we need to bind each folder to itself.

**Comment by kishwarshafin** [comment]
Not exactly to itself, but you need to bind to a path and use that path consistently. Details here: https://docs.sylabs.io/guides/3.0/user-guide/bind_paths_and_mounts.html
