### ISSUE TITLE
why no heterozygous site 

### ISSUE THREAD

**Issue by huangl07** [google/deepsomatic#3]
Dear,

I have already test the deepsomatic to run both illumina and pacbio platform

but I have find a ambiguous result that all Pass variant is no heterozygous site ,the Pass variant is all homozygous

I wander why

**Comment by pichuan** [comment]
Hi @huangl07 ,

DeepSomatic calls somatic variants. Unlike germline variants, there isn't really a notion of heterozygous variants. Anything `1/1` by DeepSomatic means it's determined as a somatic variant. 

Hope this helps! Feel free to follow up if you have more questions.

**Comment by huangl07** [comment]
well，Maybe it difficult to adapt other softwares，I have used sentieon and GATK，they put somatic variant Genotype "0/1"

and Also，it output the normal sample genotype and depth

thankyou！

**Comment by kishwarshafin** [comment]
Hi @huangl07 , 

If you want to obtain the genotype of the normal, currently the solution would be to run DeepVariant (https://github.com/google/deepvariant) on the normal bam and get the accurate genotypes.

I can lay out two things which prevented us from genotyping the normal:
1. The truth set comes from SEQC2 which only has Tumor/Normal status, it does not have normal genotypes present.
2. The intention of somatic calling is to determine normal vs tumor, genotyping the normal variants is a secondary function and there are currently methods like DeepVariant available to do it accurately.


On somatic variants being "0/1" or "1/1": somatic variants generally do not have "genotypes" as they are not inherited, so calling them "0/1" or "1/1" would be synonymous. You can use `bcftools` to convert all '1/1` to '0/1` and vice versa and it should be synonymous. Hope this helps.

**Comment by huangl07** [comment]
thankyou!

I will back if I have other questions

**Comment by kishwarshafin** [comment]
Thank you, I will close this for now. Feel free to re-open if you have more questions.
