### ISSUE TITLE
How to use HiPhase to get haplotype-specific Somatic SNV/INDEL?

### ISSUE THREAD

**Issue by DayTimeMouse** [google/deepsomatic#30]
Hi,

I saw the HiFi somatic workflow https://github.com/PacificBiosciences/HiFi-somatic-WDL/blob/main/figures/simple_workflow_diagram.png. After calling somatic SNV/INDEL(using deepsomatic, tumor/normal paired sample), then how should I do use HiPhase to get haplotype-specific Somatic SNV/INDEL?

Best regards.

**Comment by pichuan** [comment]
Hi @DayTimeMouse ,
I see that you've posted the question on https://github.com/PacificBiosciences/HiPhase/issues/52. That's a more suitable place to get your question answered. So I will close this issue now.
