### ISSUE TITLE
Question about training set data

### ISSUE THREAD

**Issue by skchronicles** [google/deepsomatic#36]
Hey @kishwarshafin,

I have a quick question. Was Deepsomatic trained on recalibrated BAM files?

Best regards,
@skchronicles

**Comment by skchronicles** [comment]
I am just wondering if it would be best to provide a recal BAM file as input to deepsomatic.

**Comment by AndrewCarroll** [comment]
Hi @skchronicles 

We did not train with BQSR-tranformed files. In our prior investigations with germline DeepVariant, we observed very little difference with files that had BQSR versus those that did not (and a very small accuracy advantage to NOT running BQSR). 

We did not investigate this with DeepSomatic. I doubt it would make much difference. If you have files prior to run BQSR, we'd recommend not to run BQSR. If you already have files processed with BQSR, it should be fine to run DeepSomatic on them.

**Comment by skchronicles** [comment]
Hey @AndrewCarroll,

Thank you for getting back in touch with me. I am reaching out because I am noticing a difference in recall when running deepsomatic/1.7.0 using SEQC2's tumor/normal pair with a sorted BAM file vs. recalibrated BAM file. 

Here are some of my initial results when using som.py:
```text
type  total.truth  total.query  tp     fp     fn     recall           precision       caller
SNPs  39447        35998        35903  95     3544   0.91015793343    0.997360964498  deepsomatic_recal_bam
SNPs  39447        30159        29901  258    9546   0.758004410982   0.9914453397    deepsomatic_sorted_bam
``` 

Using the sorted BAM file, deepsomatic is not calling/missing quite a few variants and the recall is much lower at 0.758.

I am going to run one more test on my side to determine if the issue is related to the input BAM file (sorted vs. recal) or the docker image/hardware the second step is running with. I technically made two changes when looking into this issue. I changed the input file (to use recal BAM file and I updated the second step of deepsomatic to use GPUs). Right now, I have a job running to run the second and third step of deepsomatic with a recal BAM files and using CPU docker image.

I will keep you in the loop. I should know by Monday.

Best regards,
@skchronicles

**Comment by kishwarshafin** [comment]
@skchronicles ,

If you can, please update docker to 1.8.0 if possible. Although the models are the same, there can be some difference you may observe in results. We did test BQSR vs not and did not see a big difference. Please let us know if you find something that's unusual on your end.

**Comment by skchronicles** [comment]
Hey @kishwarshafin,

Thank you for looking into this issue! I will test out deepsomatic with the latest docker image (i.e. 1.8), and I will let you know if I observe the same difference in recall. 

At the current moment, another member of our group is independently testing deepsomatic/1.7 with a sorted BAM file versus a recalibrated bam file. That testing should be done within the next day or so. I will report the results of that testing soon. 

Best regards,
@skchronicles

**Comment by kishwarshafin** [comment]
@skchronicles ,

The models did not change between 1.7 and 1.8 so I don't expect the results to be different. Providing the BAM file would be the best way for us to investigate this further.

**Comment by kishwarshafin** [comment]
@skchronicles ,

So if I understand correctly, if you "DO NOT" recalibrate the base qualities, the recall drops, is that right? The majority of our training bams come from SEQC2 (https://sites.google.com/corp/view/seqc2/home/sequencing), it seemed they didn't use recalibration (https://www.nature.com/articles/s41587-021-00993-6) but now I think they did. Thank you for doing the analysis!

**Comment by skchronicles** [comment]
Hey @kishwarshafin,

> So if I understand correctly, if you "DO NOT" recalibrate the base qualities, the recall drops, is that right?

Yes, that is correct. For the round of testing where we observed low recall, a coordinate-sorted & duplicate-marked BAM file was provided as input to deepsomatic.

Thank you for taking some time out of your day to look into this issue more. We will use recalibrated BAM files with deepsomatic.

**Comment by skchronicles** [comment]
Hey @AndrewCarroll @kishwarshafin,

I just wanted to provide a quick update in relationship to using the current version of deepsomatic (1.8.0) as of today.

Here are the results of using deepsomatic with a sorted, markdups BAM file vs. a recalibrated BAM file using deepsomatic/1.7.0 and deepsomatic/1.8.0:

**deepsomatic/1.7.0**

```
type  total.truth  total.query  tp     fp     fn     recall           precision       caller
SNPs  39447        35998        35903  95     3544   0.91015793343    0.997360964498  deepsomatic_recal_bam
SNPs  39447        30159        29901  258    9546   0.758004410982   0.9914453397    deepsomatic_sorted_bam
```

**deepsomatic/1.8.0**

```
type  total.truth  total.query  tp     fp     fn    recall          precision       caller
SNPs  39447        35998        35903  95     3544  0.91015793343   0.997360964498  deepsomatic_recal_bam
SNPs  39447        30169        29911  258    9536  0.758257915684  0.991448175279  deepsomatic_sorted_bam
```


As you mentioned eariler @kishwarshafin, there aren't any significant differences in the accuracy/percision between those two version of deepsomatic; however, there is a considerable speed-up between the mk_examples step between `deepsomatic/1.7.0` vs `deepsomatic/1.8.0`.

Here is some run time statistics from those two sets of tests.

**deepsomatic/1.7.0**
```
jobid     jobname          cpu_max  mem_max  elapsed_time
42778610  ds_mkexamples    38       32GB     8:30:50
42826062  ds_callvars_gpu  33       14GB     1:13:04
42831837  ds_postprovars   6        45GB     13:17
```

**deepsomatic/1.8.0**

```
jobid     jobname          cpu_max  mem_max  elapsed_time
43172319  ds_mkexamples    38       22GB     6:01:08
43219931  ds_callvars_gpu  75       14GB     1:20:04
43222416  ds_postprovars   6        45GB     13:10
```

As seen above, there is a 2 hour and 30 minute speed-up of the first step in the deepsomatic pipeline when using  `deepsomatic/1.8.0`.  The second step was on an A100 GPU while the first and third steps were run on compute instances. With that being said, if anyone is using `deepsomatic/1.7.0` it may be worth upgrading to `deepsomatic/1.8.0`. 

With that being said, I would highly recommend using recalibrated BAM files (if possible), for more information as to how to produce these recalibrated BAM files, you can reference this [Snakefile](https://github.com/OpenOmics/genome-seek/blob/v0.9.0/workflow/rules/gatk_recal.smk).
