### ISSUE TITLE
DeepSomatic freezes after call_variants when there is 0 example

### ISSUE THREAD

**Issue by proteinosome** [google/deepsomatic#8]
@kishwarshafin Khi PIn here. Filing a report of an issue I'm seeing. I'm trying to implement DeepSomatic into a pipeline. What the pipeline does now is that it splits the genome into equal interval and uses the `--region` parameter to call variants in just that region. However, when I was testing this with a toy example which doesn't have variants in most intervals, the DeepSomatic step stops progressing after `call_variants`. 

Attaching a zip file of the log files collected here with the command used (`command` file). Thanks.

[logs.zip](https://github.com/google/deepsomatic/files/13315975/logs.zip)

**Comment by kishwarshafin** [comment]
Hi @proteinosome , Thank you very much for reporting this. I can confirm this is reproducible. I will work on a fix soon.

**Comment by kishwarshafin** [comment]
hi @proteinosome , we are currently fixing this issue. We will push a fix very soon.

**Comment by kishwarshafin** [comment]
This issue should be fixed in 1.6.1, please feel free to reopen if you that's not the case.
