### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files

### ISSUE THREAD

**Issue by lixingqiancs** [google/deepsomatic#9]
I got this error when I used singularity to run deepsomatic.

tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /opt/models/deepsomatic/wgs      

Please give me some suggestion, thanks! 

![image](https://github.com/google/deepsomatic/assets/44748328/e9c5cec9-818a-45da-8948-1449186a3ea4)

**Comment by lixingqiancs** [comment]
INPUT_DIR="/mnt/dt2_dc2stor_data202/my/"

singularity exec \
    -B ${INPUT_DIR} \
    /mnt/dt2_dc2stor_data202/my/software/deepvariant/v1.6/deepvariant_1.6.0.sif \
    run_deepsomatic \
    --model_type WGS \
    --ref ${INPUT_DIR}/database/deepvariant/reference/GRCh38_no_alt_analysis_set.fasta \
    --reads_normal=${normal_bam} \
    --reads_tumor=${tumor_bam}  \
    --output_vcf ${workdir}/output.vcf.gz \
    --output_gvcf ${workdir}/output.g.vcf.gz \
    --sample_name_tumor="tumor" \
    --sample_name_normal="normal" \
    --num_shards $1 \
    --logging_dir=${workdir}/logs\
    --intermediate_results_dir ${workdir}/intermediate_results_dir

**Comment by lixingqiancs** [comment]
> @lixingqiancs ,
> 
> Can you please provide the command you are running which results in this error?

INPUT_DIR="/mnt/dt2_dc2stor_data202/my/"

singularity exec
-B ${INPUT_DIR}
/mnt/dt2_dc2stor_data202/my/software/deepvariant/v1.6/deepvariant_1.6.0.sif
run_deepsomatic
--model_type WGS
--ref ${INPUT_DIR}/database/deepvariant/reference/GRCh38_no_alt_analysis_set.fasta
--reads_normal=${normal_bam}
--reads_tumor=${tumor_bam}
--output_vcf ${workdir}/output.vcf.gz
--output_gvcf ${workdir}/output.g.vcf.gz
--sample_name_tumor="tumor"
--sample_name_normal="normal"
--num_shards $1
--logging_dir=${workdir}/logs
--intermediate_results_dir ${workdir}/intermediate_results_dir

**Comment by kishwarshafin** [comment]
@lixingqiancs , 

Looks like a file mounting issue. Can you please add this to your singularity command and see if that helps:

```bash
-B /usr/lib/locale/:/usr/lib/locale/
```

**Comment by lixingqiancs** [comment]
> @lixingqiancs ,
> 
> Looks like a file mounting issue. `call_variants` can't find the model file located in `/opt/`. Can you please add this to your singularity command and see if that helps:
> 
> ```shell
> -B /usr/lib/locale/:/usr/lib/locale/
> ```

I checked the docker image. It seems don't have the somatic model. Could you help me to check?

![image](https://github.com/google/deepsomatic/assets/44748328/1df5d01b-8260-4125-9898-357eadb381f6)
![image](https://github.com/google/deepsomatic/assets/44748328/df5d6c8b-ae97-4f20-bf99-db3ecd2e2634)

**Comment by kishwarshafin** [comment]
Ah, you are using the wrong docker. Sorry I missed it the first time:

Please use:
```bash
docker pull google/deepsomatic:1.6.0
```

**Comment by lixingqiancs** [comment]
> Ah, you are using the wrong docker. Sorry I missed it the first time:
> 
> Please use:
> 
> ```shell
> docker pull google/deepsomatic:1.6.0
> ```

That's work!!! Thanks so much for your important suggestion.
